alter session set container = xepdb1;

-- CREATE USER
CREATE USER demouser IDENTIFIED BY demopass
  DEFAULT TABLESPACE users
  QUOTA 100M ON users;

GRANT CREATE SESSION TO demouser;
GRANT CREATE TABLE TO demouser;
GRANT DELETE ANY TABLE TO demouser;
GRANT UPDATE ANY TABLE TO demouser;
GRANT INSERT ANY TABLE TO demouser;
GRANT SELECT ANY TABLE TO demouser;
GRANT CREATE SEQUENCE TO demouser;
GRANT CREATE ANY INDEX TO demouser;
GRANT SELECT ANY DICTIONARY TO demouser;