version: '3.8'
services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_PWD=sys
    ports:
      - "1521:1521"
      - "5500:5500"
      - "2484:2484"
    volumes:
      # Oracle's storage folder - the database will survive the restarts
      - ./oracle/storage:/opt/oracle/oradata
      # Oracle's startup and setup scripts folder - https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance#running-scripts-after-setup-and-on-startup
      - ./oracle/scripts:/opt/oracle/scripts